logging:
  level:
    org.springframework: INFO

application:
  about:
    name: "Fabio Rafael"
    email: "fdr@fabiodarosa.org"
    social:
      github: "github.com/fbodr"
      gitlab: "gitlab.com/fbodr"
      twitter: "@fdobr"
      mastodon: "@fbodr@mastodon.social"
